// <auto-generated />
using BonusBot.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BonusBot.Database.Migrations
{
    [DbContext(typeof(BonusDbContext))]
    [Migration("20210214120023_Remove_GuildCoresettings")]
    partial class Remove_GuildCoresettings
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("BonusBot.Database.Entities.Settings.BotSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefaultName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BotSettings");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            DefaultName = "BonusBot"
                        });
                });

            modelBuilder.Entity("BonusBot.Database.Entities.Settings.GuildsSettings", b =>
                {
                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Module")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("GuildId", "Key", "Module");

                    b.ToTable("GuildsSettings");
                });
#pragma warning restore 612, 618
        }
    }
}
